---

# there is no ansible_effective_user_dir
- name: set $HOME
  set_fact:
    r_gnome_extensions_home: "{{ lookup('env', 'HOME') }}"

- name: Check if Gnome Shell extension is already installed - {{ gnome_extension_info.name }}
  stat:
    path: "{{ r_gnome_extensions_home }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}/metadata.json"
  register: r_gnome_extensions_check_existing

- name: Create temporary download directory
  tempfile:
    state: directory
    suffix: ".gnome_extension_download"
  register: r_gnome_extension_download_dir
  changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False

- block:
    - name: Download Gnome Shell extension - {{ gnome_extension_info.name }}
      get_url:
        url: https://extensions.gnome.org{{ gnome_extension_info.download_url }}
        dest: "{{ r_gnome_extension_download_dir.path }}/{{ gnome_extension_info.uuid }}.zip"
      register: r_gnome_extension_download

    - name: Install  Gnome Shell extension - {{ gnome_extension_info.name }}
      command: "/usr/bin/gnome-extensions install {{ r_gnome_extension_download_dir.path }}/{{ gnome_extension_info.uuid }}.zip"

    - name: Enable Gnome Shell extension - {{ gnome_extension_info.name }}
      command: gnome-extensions enable {{ gnome_extension_info.uuid }}
  always:
    - name: Delete temporary download directory
      file:
        path: "{{ r_gnome_extension_download_dir.path }}"
        state: absent
      changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False
