---
# tasks file for gnome-extensions

- name: Parse Gnome Shell version
  shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: r_gnome_extension_parse_shell_version
  changed_when: no

- set_fact:
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"

- name: Get Gnome Shell extension info
  uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_shell_version }}
    return_content: yes
  loop: "{{ gnome_extension_ids }}"
  register: r_gnome_extension_info

- name: Check if there is new tool /usr/bin/gnome-extensions
  stat:
    path: /usr/bin/gnome-extensions
  register: new_tool

- include_tasks: install_extension.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
  when: not new_tool.stat.exists

- include_tasks: install_extension_new.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
  when: new_tool.stat.exists
